Repository belf-kr/todo-service, pull requests merged in 2021-11, with the labels that each got.

#109 up: work-todo 생성 시 필수 컬럼만 입력 가능한 기능 추가
  src/entity/work-todo.entity.ts
  src/work-todo/work-todo.dto.ts
  src/work-todo/work-todo.http
Labels: documentation, modify

#110 up: courseId 사용해서 work done 리스트 가져오는 기능 추가
  src/work-done/work-done.controller.ts
  src/work-done/work-done.http
  src/work-done/work-done.service.ts
Labels: new feature

#111 up: DB 스키마 변경
  src/entity/work-todo.entity.ts
  src/work-done/work-done.service.ts
  src/work-todo/work-todo.dto.ts
  src/work-todo/work-todo.http
  src/work-todo/work-todo.service.ts
  src/work-todo/work-todo.type.ts
Labels: modify

#112 up: work_todo 생성 시 active_date 입력 불가능 문제 수정
  src/work-todo/work-todo.http
  src/work-todo/work-todo.service.ts
Labels: documentation, modify

#113 up: type 관련 코드 세분화
  .vscode/settings.json
  src/course/course-get.dto.ts
  src/course/course-get.interface.ts
  src/course/course-post.dto.ts
  src/course/course-post.interface.ts
  src/course/course.controller.ts
  src/course/course.dto.ts
  src/course/course.service.ts
  src/course/course.type.ts
  src/work-todo/work-todo-get.dto.ts
  src/work-todo/work-todo-get.interface.ts
  src/work-todo/work-todo-post.dto.ts
  src/work-todo/work-todo-post.interface.ts
  src/work-todo/work-todo.controller.ts
  src/work-todo/work-todo.dto.ts
  src/work-todo/work-todo.service.ts
  src/work-todo/work-todo.type.ts
Labels: modify

#114 up: work todo 테이블 속 반복 요일 입력, 출력 기능 추가
  package-lock.json
  package.json
  src/course/course-get.dto.ts
  src/course/course.http
  src/course/course.service.ts
  src/repeated-days-of-the-week/repeated-days-of-the-week.module.ts
  src/work-done/work-done.service.ts
  src/work-todo/work-todo-get.dto.ts
  src/work-todo/work-todo-get.interface.ts
  src/work-todo/work-todo-post.dto.ts
  src/work-todo/work-todo-post.interface.ts
  src/work-todo/work-todo.controller.ts
  src/work-todo/work-todo.dto.ts
  src/work-todo/work-todo.http
  src/work-todo/work-todo.module.ts
  src/work-todo/work-todo.service.ts
Labels: new feature, modify

#116 ping 응답시 express response 객체에 직접 접근하는 코드 삭제
  src/app.controller.ts
Labels: modify

#117 JS 모듈을 import 하는 코드를 권장 방법으로 수정
  src/app.module.ts
  src/config/typeorm.config.ts
  test/app.e2e-spec.ts
Labels: modify

#118 Controller 코드에서 Service 코드 호출 시 json을 파라미터로 입력받게 수정
  src/work-done/work-done-querystring.dto.ts
  src/work-done/work-done-querystring.type.ts
  src/work-done/work-done.controller.ts
  src/work-done/work-done.service.ts
  src/work-todo/work-todo-querystring.dto.ts
  src/work-todo/work-todo-querystring.type.ts
  src/work-todo/work-todo.controller.ts
  src/work-todo/work-todo.service.ts
Labels: modify

#121 work_done 생성시 userId 값을 유저의 요청에서 받아오게 코드 수정
  src/course/course.http
  src/entity/work-done.entity.ts
  src/work-done/work-done.http
Labels: bug

#122 한 일을 추가할 시 검증 로직 추가
  src/work-done/work-done.service.ts
Labels: bug, modify

#123 work_todo 테이블 내 user_id 컬럼 추가
  src/entity/course.entity.ts
  src/entity/work-done.entity.ts
  src/entity/work-todo.entity.ts
  src/work-todo/work-todo.dto.ts
  src/work-todo/work-todo.service.ts
  src/work-todo/work-todo.type.ts
Labels: modify

#124 Get, Delete 요청시 userId를 query string에서 가져와 필터링 하는 기능 추가
  src/common/lib/error.ts
  src/course/course-querystring.dto.ts
  src/course/course-querystring.type.ts
  src/course/course.controller.ts
  src/course/course.dto.ts
  src/course/course.http
  src/course/course.service.ts
  src/work-done/work-done-querystring.dto.ts
  src/work-done/work-done-querystring.type.ts
  src/work-done/work-done.controller.ts
  src/work-done/work-done.dto.ts
  src/work-done/work-done.http
  src/work-done/work-done.service.ts
  src/work-todo/work-todo-querystring.dto.ts
  src/work-todo/work-todo-querystring.type.ts
  src/work-todo/work-todo.controller.ts
  src/work-todo/work-todo.http
  src/work-todo/work-todo.service.ts
Labels: bug, new feature, modify

#125 work-todo 조건에 따라 리스트 조회시 SQL 쿼리 1회 실행으로 변경
  src/entity/course.entity.ts
  src/entity/work-todo.entity.ts
  src/work-todo/work-todo.http
  src/work-todo/work-todo.service.ts
Labels: modify

#126 반복 일수에 따라 반복되는 work-todo 리스트 가져오는 기능 추가, userId 필수여부 삭제
  package-lock.json
  package.json
  src/course/course-querystring.dto.ts
  src/course/course-querystring.type.ts
  src/course/course.controller.ts
  src/work-done/work-done-querystring.dto.ts
  src/work-done/work-done-querystring.type.ts
  src/work-done/work-done.controller.ts
  src/work-done/work-done.service.ts
  src/work-todo/work-todo-querystring.dto.ts
  src/work-todo/work-todo-querystring.type.ts
  src/work-todo/work-todo.controller.ts
  src/work-todo/work-todo.http
  src/work-todo/work-todo.service.ts
Labels: new feature, modify

#127 Course 리스트 가져오는 메소드 이름 변경
  src/course/course.controller.ts
  src/course/course.http
  src/course/course.service.ts
Labels: modify

#128 Course Id 사용해 특정 course 가져오는 기능 추가
  src/course/course-querystring.dto.ts
  src/course/course-querystring.type.ts
  src/course/course.controller.ts
  src/course/course.http
  src/course/course.service.ts
Labels: new feature, modify

#132 course 테이블 내부의 creator_id 컬럼명 변경, typeorm migration용 코드 추가, K8S 리소스 변경
  .env.dev
  Dockerfile
  README.md
  docker-compose.yml
  k8s/prod.yaml
  k8s/qa.yaml
  package.json
  src/app.module.ts
  src/config/database.config.ts
  src/config/typeorm/env.ts
  src/config/typeorm/typeorm.config.ts
  src/course/course.dto.ts
  src/course/course.http
  src/course/course.service.ts
  src/course/course.type.ts
  src/entity/course.entity.ts
  src/migrations/1637464140864-CourseUsernameRename.ts
  src/work-done/work-done.service.ts
Labels: new feature, modify, k8s

#135 VSCode 사용한 디버깅 환경 설정 파일 추가
  .vscode/launch.json
  README.md
  k8s/prod.yaml
  k8s/qa.yaml
  package-lock.json
  package.json
Labels: documentation

#136 v0.7.0
  .vscode/launch.json
  README.md
  k8s/prod.yaml
  k8s/qa.yaml
  package-lock.json
  package.json
Labels: documentation, k8s

#137 서비스 로직 처리 시간 로깅 기능 추가
  src/app.module.ts
  src/color/color.http
  src/interceptor/logging.interceptor.ts
Labels: new feature

#138 TypeORM 사용해 DB Schema 동기화 방법 설명 추가
  README.md
  readme/img/create-typeorm-migration-class.png
  readme/img/realize-interface.png
  readme/img/revert-migration-command.png
  readme/img/run-migration-command.png
Labels: documentation

#139 k8s 컨테이너 상태 모니터링 추가
  k8s/prod.yaml
  k8s/qa.yaml
Labels: k8s

#140 로컬 개발용 docker파일 추가
  docker-compose.yml
  docker/mysql/Dockerfile
  docker/mysql/init.sql
  docker/mysql/master/docker-compose.yml
  docker/mysql/slave1/Dockerfile
  docker/mysql/slave1/docker-compose.yml
  docker/mysql/slave1/init.sql
Labels: new feature

#143 work-todo id 사용해 가져오는 기능 추가
  src/work-todo/work-todo-querystring.dto.ts
  src/work-todo/work-todo.controller.ts
  src/work-todo/work-todo.http
  src/work-todo/work-todo.service.ts
Labels: new feature

#144 work-todo 조회시 courseId 가져오는 기능 추가
  src/work-todo/work-todo-get.dto.ts
  src/work-todo/work-todo-get.interface.ts
  src/work-todo/work-todo.service.ts
Labels: new feature
