Repository belf-kr/todo-service, pull requests merged in 2021-12, with the labels that each got.

#146 DB Insert 후 PK 가져오던 SQL SELECT 구문 삭제
  src/color/color.service.ts
  src/common/crud.service.ts
  src/course/course.controller.ts
  src/course/course.service.ts
  src/work-done/work-done.service.ts
  src/work-todo/work-todo.controller.ts
  src/work-todo/work-todo.service.ts
Labels: modify

#145 README.md내 docker 사용해 빠른 시작 설명 추가
  README.md
Labels: documentation

#147 버전 정보 업데이트
  .gitignore
  .vscode/launch.json
  README.md
  package-lock.json
  package.json
Labels: documentation

#149 course import 기능 추가
  src/app.module.ts
  src/course-importation/course-importation.dto.ts
  src/course-importation/course-importation.module.ts
  src/course-importation/course-importation.service.spec.ts
  src/course-importation/course-importation.service.ts
  src/course-importation/course-importation.type.ts
  src/course/course.controller.ts
  src/course/course.http
  src/course/course.module.ts
  src/course/course.service.ts
  src/entity/course.entity.ts
  src/entity/work-done.entity.ts
  src/migrations/1638459992793-CourseColumnRelationChange.ts
  src/tag/tag.querystring.dto.ts
  src/tag/tag.querystring.type.ts
  src/tag/tag.service.ts
  src/work-done/work-done.http
  src/work-done/work-done.module.ts
  src/work-todo/work-todo.module.ts
  src/work-todo/work-todo.service.ts
Labels: new feature

#150 work_done 내부의 action_date 컬럼 not null하게 변경
  src/entity/work-done.entity.ts
  src/migrations/1638951784430-WorkDoneSchemaModify.ts
Labels: modify

#151 work-done 생성시 기본값으로 현재 시간 들어가도록 변경
  src/work-done/work-done.service.ts
Labels: modify

#152 work-todo 컬럼값으로 삭제 구분 기능 추가
  src/entity/work-todo.entity.ts
  src/work-todo/work-todo.service.ts
Labels: new feature

#153 course import 버그 수정
  src/course/course-querystring.dto.ts
  src/course/course.controller.ts
  src/course/course.http
  src/course/course.service.ts
Labels: bug

#155 course import시 color 정보 미입력 문제 수정
  src/course/course.service.ts
Labels: bug

#156 코스 제목 검색하는 기능 추가
  src/course/course.controller.ts
  src/course/course.http
  src/course/course.service.ts
Labels: new feature

#157 work-todo 내부에 기존 explanation 데이터 입력
  src/course/course.controller.ts
  src/course/course.http
  src/work-todo/work-todo.service.ts
Labels: bug

#158 userId로 work-done 조회시 work-todo 없는 경우에 대한 처리
  src/work-done/work-done.service.ts
Labels: bug

#159 코스 제목 검색시 색상 정보 조회 않되는 문제 수정
  src/course/course.service.ts
Labels: bug

#160 course 조회시 user email 정보 반환 기능 추가
  src/course/course-get.dto.ts
  src/course/course-get.interface.ts
  src/course/course.service.ts
Labels: new feature

#161 user 조회시 DB connection pool release 코드 추가
  src/course/course.service.ts
Labels: bug

#162 코스 제목 검색 키워드 존재하지 않는 경우 비어있는 배열 반환
  src/course/course.service.ts
  src/entity/course.entity.ts
Labels: bug

#163 work-todo 반환값 업는 경우 전체조회 버그 수정
  src/work-done/work-done.service.ts
Labels: bug

#164 course 조회시 color 정보가 반환되지 않는 문제
  .github/workflows/aks-prod-deploy.yaml
  .github/workflows/aks-qa-deploy.yaml
  .github/workflows/aks-test-deploy.yaml
  src/course/course.service.ts
Labels: bug

#165 버전 정보 업데이트
  package-lock.json
  package.json
  src/app.controller.ts
  src/course/course.http
Labels: modify

#167 TypeORM 타임존 옵션을 Zulu time으로 변경
  src/config/database.config.ts
Labels: modify

#168 유저 탈퇴 기능 추가
  src/app.module.ts
  src/course-importation/course-importation.service.ts
  src/course/course.http
  src/course/course.service.ts
  src/entity/work-todo.entity.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.http
  src/user/user.module.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
  src/work-done/work-done.service.ts
  src/work-todo/work-todo.service.ts
Labels: new feature

#169 course가 존재하지 않는 work-todo 조회시 500 응답 수정
  src/work-todo/work-todo.service.ts
Labels: bug

#170 course import시 오늘 날자 및 시간 + (work done 시간 및 날짜 - work-todo 시간 및 날짜) 입력하는 기능 추가
  src/course/course.http
  src/course/course.service.ts
  src/entity/course.entity.ts
  src/migrations/1639657054999-CourseDeleteNullableStartDate.ts
  src/work-todo/work-todo.service.ts
Labels: new feature

#171 work-todo 내부의 courseId 옵션 cascade로 변경
  src/entity/work-todo.entity.ts
  src/migrations/1639667174402-WorkTodoAddFKConstraint.ts
  src/work-todo/work-todo.service.ts
Labels: modify

#174 oauth-server DB 공유하는 코드를 제거하여 결합성 제거, 문서 보강
  .env.dev
  README.md
  docker-compose.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/common/lib/oauth-api.ts
  src/common/lib/service.ts
  src/course/course.module.ts
  src/course/course.service.ts
Labels: bug, modify
